---
title: "Análisis de la Producción"
output: 
  html_document:
            toc: TRUE
            toc_float: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE}
#Librerias
library(DT)
library(visNetwork)
library(ggraph)
library(plotly)
library(readr)
library(tidyverse)
library(tidymodels)
library(tidygraph)
library(here)
library(igraph)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, cache=FALSE}
info <- 
  read_csv(here("data", "Workshop.csv"))

graph_tbl <- 
  info |> 
  graph_from_data_frame(directed = FALSE) |> 
  as_tbl_graph() |> 
  convert(to_simple) |> 
  activate(nodes)
```

## Vista red grafos

```{r, echo=FALSE, warning=FALSE, message=FALSE, cache=FALSE}
colores <- c('red','green', 'black')
nodes <- 
  graph_tbl |> 
  activate(nodes) |>
  mutate(color=as.character(group_louvain())) |>
  #grado
  mutate(value = centrality_degree(),
         value = value *5) |> 
  mutate(id = row_number()) |>
  data.frame() |> 
  rename(label = name) |> 
  mutate(color = colores[color])

edges_1 <- 
  graph_tbl |> 
  activate(nodes) |> 
  activate(edges) |> 
  data.frame() |> 
  rename(fortaleza = 3) |> 
  select(from, to, fortaleza)

width = c()
for(i in edges_1$fortaleza){
  width <- append(width, length(i))
}

width = as.data.frame(width)
edges <- cbind(edges_1, width)|> 
  mutate(width = width*5)

visNetwork(nodes = nodes, 
           edges = edges, 
           width = "100%") |> 
  visExport() |> 
  visLegend() |> 
  visOptions(highlightNearest = list(enabled = T, degree = 1, hover = T),
             manipulation = list(enabled = TRUE, 
                                 editEdgeCols = c("label"), 
                                 editNodeCols = c("group"), 
                                 addNodeCols = c("id", "label"))) |>
  visLayout(randomSeed = 12) |> 
  visPhysics(solver ='forceAtlas2Based', 
             stabilization = FALSE)
# |>
#   for(i in nodes_u$community)
#   {
#     visGroups(groupname = i, color = "red")
#   }

#  visNodes(color = "red", size = nodes$degree)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, cache=FALSE}
# importación
# imagen <- graph_from_data_frame(d = edges,
#                       directed = FALSE,
#                       vertices = nodes) |>
#   write_graph("academic_social_network_universidades.graphml",
#               "graphml")
```

## Datos tabla

```{r, echo=FALSE, warning=FALSE, message=FALSE, cache=FALSE}
graph_tbl|> 
  activate(nodes) |>
  mutate(community=as.character(group_louvain())) |>
  #grado
  mutate(degree = centrality_degree()) |>
  data.frame() |> 
  select("Label" = name,
         "Grado" = degree,
         "Comunidad" = community) |>
  DT::datatable(class = "cell-border stripe", 
                rownames = F, 
                filter = "top", 
                editable = FALSE, 
                extensions = "Buttons", 
                options = list(dom = "Bfrtip",
                               buttons = c("copy",
                                           "csv",
                                           "excel", 
                                           "pdf", 
                                           "print")))
```

